ingress:
  # className: ""
  # host: ontopic.local
  tls: false
  # secretName: ontopic-suite-tls
  # annotations: {}

process-server:
  secrets:
    user-license-file: /run/secrets/user-license

store-server:
  env:
    database_host: store-server-db-postgresql.ontopic.svc.cluster.local
    database_port: 5432
    database_name: internal
    database_user: postgres
    casbin_store_host: store-server-db-postgresql.ontopic.svc.cluster.local
    casbin_store_port: 5432
    casbin_store_user: postgres
    ontopic_server_host: http://ontopic-server.ontopic.svc.cluster.local:8080
  secrets:
    database-password-file: /run/secrets/database-password-file

web:
  env:
    ONTOP_ENDPOINT_SERVICE_HOST: ontopic-server.ontopic.svc.cluster.local
    # virtual_host: ontopic.local

# Create users
users:
  # -- enable the user creation job
  enabled: true
  # -- list of users to create
  list:
    - username: admin
      password: "$aprBe1/"
      email: test@email.it
      fullname: Admin
      groups:
        - developers
        - admin
    - username: test
      password: "$apr1$C."
      email: test@email.it
      fullname: Test
      groups:
        - developers

# Configure the PostgreSQL subchart
postgresql:
  # -- enable the PostgreSQL chart
  enabled: true
  # -- enable creation of the secret for Ontopic Suite
  enableSecretCreation: true
  # -- enable creation of the "internal" database
  enableDatabaseCreation: true
  # -- enable demo data
  enableDemoData: false

# Configure the Ontopic Server subchart
ontopic-server:
  # -- enable the Ontopic Server chart
  enabled: true
