ingress:
  # className: ""
  host: ontopic.local  # Set your domain here (must match web.env.virtual_host)
  tls: false
  # secretName: ontopic-suite-tls

# Create users
users:
  # -- enable the user creation job
  enabled: true
  # -- list of users to create
  list:
    - username: test
      password: "test"
      email: test@email.it
      fullname: Test
      groups: []
      roles:
        - ots-admin

# Configure the PostgreSQL subchart
db:
  # -- enable demo data
  enableDemoData: true