apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ontopic-server.fullname" . }}
  labels:
    {{- include "ontopic-server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ontopic-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ontopic-server.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ontopic-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if and .Values.jdbcExternal.enabled .Values.jdbcExternal.replaceExistingDrivers }}
          command:
            - sh
            - -c
            - |
              echo "Clearing existing JDBC drivers..."
              rm -rf {{ .Values.env.ONTOPIC_SERVER_JDBC_ROOT_DIR }}/*
              echo "Starting ontopic-server..."
              exec /opt/ontopic-server/entrypoint.sh
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{.Values.envConfigMapName  | quote}}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: postgres
              containerPort: 4300
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if or .Values.secrets .Values.optionalSecrets }}
          volumeMounts:
          {{- range $name, $mount := .Values.secrets }}
            - name: "{{ $name }}-volume"
              mountPath: {{ $mount | quote }}
          {{- end }}
          {{- if .Values.optionalSecrets }}
          {{- range $name, $config := .Values.optionalSecrets }}
          {{- if lookup "v1" "Secret" $.Release.Namespace $name }}
            - name: "{{ $name }}-volume"
              mountPath: {{ $config.mountPath | quote }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- end }}
          {{- include "ontopic-server.volumeMount" (dict "config" .Values.endpoint) | nindent 12 }}
          {{- include "ontopic-server.volumeMount" (dict "config" .Values.endpointSecurity) | nindent 12 }}
          {{- include "ontopic-server.volumeMount" (dict "config" .Values.materializationDb) | nindent 12 }}
          {{- include "ontopic-server.volumeMount" (dict "config" .Values.materializationConfiguration) | nindent 12 }}
          {{- include "ontopic-server.volumeMount" (dict "config" .Values.materializationResult) | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- range $name, $mount := .Values.secrets }}
        - name: "{{$name}}-volume"
          secret:
            secretName: {{$name | quote}}
      {{- end }}
      {{- if .Values.optionalSecrets }}
      {{- range $name, $config := .Values.optionalSecrets }}
      {{- if lookup "v1" "Secret" $.Release.Namespace $name }}
        - name: "{{$name}}-volume"
          secret:
            secretName: {{$name | quote}}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- include "ontopic-server.volume" (dict "config" .Values.endpoint "context" $) | nindent 6 }}
      {{- include "ontopic-server.volume" (dict "config" .Values.endpointSecurity "context" $) | nindent 6 }}
      {{- include "ontopic-server.volume" (dict "config" .Values.materializationDb "context" $) | nindent 6 }}
      {{- include "ontopic-server.volume" (dict "config" .Values.materializationConfiguration "context" $) | nindent 6 }}
      {{- include "ontopic-server.volume" (dict "config" .Values.materializationResult "context" $) | nindent 6 }}
  {{- if .Values.persistentVolumeClaimRetentionPolicy.enabled }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: {{ .Values.persistentVolumeClaimRetentionPolicy.whenDeleted }}
    whenScaled: {{ .Values.persistentVolumeClaimRetentionPolicy.whenScaled }}
  {{- end }}
  volumeClaimTemplates:
  {{- include "ontopic-server.volumeClaimTemplate" (dict "config" .Values.endpoint "context" $) | nindent 2 }}
  {{- include "ontopic-server.volumeClaimTemplate" (dict "config" .Values.endpointSecurity "context" $) | nindent 2 }}
  {{- include "ontopic-server.volumeClaimTemplate" (dict "config" .Values.materializationDb "context" $) | nindent 2 }}
  {{- include "ontopic-server.volumeClaimTemplate" (dict "config" .Values.materializationConfiguration "context" $) | nindent 2 }}
  {{- include "ontopic-server.volumeClaimTemplate" (dict "config" .Values.materializationResult "context" $) | nindent 2 }}
