{{- if not (and .Values.auth .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and .Values.auth .Values.auth.postgresPassword }}
  postgres-password: {{ .Values.auth.postgresPassword | b64enc | quote }}
  {{- else }}
  {{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (include "postgresql.fullname" .) }}
  {{- if and $existingSecret $existingSecret.data (index $existingSecret.data "postgres-password") }}
  postgres-password: {{ index $existingSecret.data "postgres-password" }}
  {{- else }}
  postgres-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
