{{- range $name, $values := .Values.services }}
{{- with $values }}
{{- if .service -}}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "ontopic-suite.name" $ }}-{{ .service.name }}"
  labels:
    {{- include "ontopic-suite.labels" $ | nindent 4 }}
  {{- with .service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .service.type }}
  ports:
    - port: {{ .service.port }}
      targetPort: {{ .service.targetPort }}
      protocol: TCP
      name: {{ .service.name }}
  selector:
    {{- include "ontopic-suite.selectorLabels" $ | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
