{{- range $name, $values := .Values.services }}
{{- with $values }}
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{.envConfigMapName}}
data:
{{- if and (hasKey $.Values $name) (hasKey (get $.Values $name) "env") }}
{{- $env := merge (get $.Values $name).env .env }}
{{- include "ontopic-studio.env" $env }}
{{- else }}
{{- include "ontopic-studio.env" .env }}
{{- end }}
{{- end }}
{{- end }}
